{"name": "test_fail7", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail7():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:20: AssertionError"}, "start": 1741458130840, "stop": 1741458130840, "uuid": "0e79e557-ba20-42b4-92f1-a75c9ee1c0c7", "historyId": "737044f4e6bfa4f10c623aa58f093eee", "testCaseId": "e5476871c2923afbd50a8191a77cef77", "fullName": "tests.simple.test_fail#test_fail7", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MBP16M1MAX.local"}, {"name": "thread", "value": "49676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}